version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:7.0.4
    ports:
      - "6379:6379"
    volumes:
      - ~/data/bisheng-data/redis/data:/data
      - ~/data/bisheng-data/redis/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf
    networks:
        proxy:
          ipv4_address: 172.30.0.2

  mysql:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=alexhope"  # 数据库密码，建议修改，如果修改需要同步修改bisheng/congfig/config.yaml配置
      - "MYSQL_DATABASE=bisheng"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - ~/data/bisheng-data/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ~/data/bisheng-data/mysql/data:/var/lib/mysql
    networks:
      proxy:
        ipv4_address: 172.30.0.3

  backend:
    # image: dataelement/bisheng-backend:v0.1.9.5
    image: local-bisheng-backend:v0.1.9.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ~/data/bisheng-data/bisheng/config/config.yaml:/app/bisheng/config.yaml
      - ~/data/bisheng-data/bisheng/data/:/app/data/
    ports:
      - "7860:7860"
    security_opt:
      - seccomp:unconfined
    command: bash -c "uvicorn bisheng.main:app --host 0.0.0.0 --port 7860 --workers 4" # --workers 表示使用几个进程，提高并发度
    restart: on-failure
    depends_on:
      - "mysql"
      - "redis"
    networks:
      proxy:
        ipv4_address: 172.30.0.4

  nginx:
    # image: dataelement/bisheng-frontend:v0.1.9.5
    image: local-bisheng-fronted:v0.1.9.5
    ports:
      - "3001:3001"
    volumes:
      - ~/data/bisheng-data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/data/bisheng-data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      proxy:
        ipv4_address: 172.30.0.5

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ~/data/bisheng-data/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
        proxy:
          ipv4_address: 172.30.0.6

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: jhchenminioadmon
      MINIO_SECRET_KEY: alexhope426minioadmon
    volumes:
      - ~/data/bisheng-data/volumes/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
    networks:
      proxy:
        ipv4_address: 172.30.0.7

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.2.10
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      minio.accessKeyID: jhchenminioadmon
      minio.secretAccessKey: alexhope426minioadmon
    volumes:
      - ~/data/bisheng-data/volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      proxy:
        ipv4_address: 172.30.0.8

  bishengrt:
    container_name: bisheng_rt_v00x
    image: dataelement/bisheng-rt:0.0.4
    # image: bisheng-rt-modify
    working_dir: /opt/bisheng-rt
    command: ./bin/rtserver f
    #  for elem model
    # command: bash bin/entrypoint.sh --serveraddr="10.10.42.114"
    shm_size: 10gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    #   - "9002:9002"
    volumes:
      - /home/station/data/bisheng-data/models:/opt/bisheng-rt/models/model_repository
    networks:
      proxy:
        ipv4_address: 172.30.0.9

  unstructured:
    container_name: bisheng_uns_v001
    image: dataelement/bisheng-unstructured:0.0.2
    working_dir: /opt/bisheng-unstructured
    command: bash bin/entrypoint.sh
    ports:
      - "10001:10001"
    networks:
      proxy:
        ipv4_address: 172.30.0.10

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
    #   - "xpack.security.enabled=false"
    volumes:
      - /home/station/data/bisheng-data/elasticsearch/data:/usr/share/elasticsearch/data
      - /home/station/data/bisheng-data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /home/station/data/bisheng-data/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      proxy:
        ipv4_address: 172.30.0.11

networks:
  proxy:
    ipam:
      config:
        - subnet: 172.30.0.0/16